name: Docker build with shared workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  docker-build:
    uses: cellpointdigital/github-reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      push: ${{ github.event_name != 'pull_request' }} # Push condition
      image_name: phpfpmextras # Image name configuration